/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author evrob0095
 */
public class methods extends javax.swing.JFrame {

    /**
     * Creates new form methods
     */
    public methods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        toRadTitle = new javax.swing.JLabel();
        maxText2 = new javax.swing.JTextField();
        minText2 = new javax.swing.JTextField();
        toRadButton = new javax.swing.JButton();
        maxTitle = new javax.swing.JLabel();
        maxText1 = new javax.swing.JTextField();
        hypoText2 = new javax.swing.JTextField();
        maxButton = new javax.swing.JButton();
        minTitle = new javax.swing.JLabel();
        minText1 = new javax.swing.JTextField();
        minButton = new javax.swing.JButton();
        powTitle = new javax.swing.JLabel();
        powText1 = new javax.swing.JTextField();
        powText2 = new javax.swing.JTextField();
        powButton = new javax.swing.JButton();
        hypoTitle = new javax.swing.JLabel();
        hypoText1 = new javax.swing.JTextField();
        hypoButton = new javax.swing.JButton();
        floorTitle = new javax.swing.JLabel();
        floorText1 = new javax.swing.JTextField();
        floorButton = new javax.swing.JButton();
        cielTitle = new javax.swing.JLabel();
        cielText1 = new javax.swing.JTextField();
        cielButton = new javax.swing.JButton();
        sqrtTitle = new javax.swing.JLabel();
        sqrtText1 = new javax.swing.JTextField();
        toRadText1 = new javax.swing.JTextField();
        sqrtButton = new javax.swing.JButton();
        answer = new javax.swing.JLabel();
        calculationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 18)); // NOI18N
        titleLabel.setText("Math Methods");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        toRadTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        toRadTitle.setText("cONVERTS A VALUE IN DEGREES TO RADIANS");
        jPanel1.add(toRadTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        maxText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxText2ActionPerformed(evt);
            }
        });
        jPanel1.add(maxText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 30, -1));

        minText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minText2ActionPerformed(evt);
            }
        });
        jPanel1.add(minText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 30, -1));

        toRadButton.setText("Calculate");
        toRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toRadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        maxTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        maxTitle.setText("Finds maximum of two numbers");
        jPanel1.add(maxTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        maxText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxText1ActionPerformed(evt);
            }
        });
        jPanel1.add(maxText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 30, -1));

        hypoText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypoText2ActionPerformed(evt);
            }
        });
        jPanel1.add(hypoText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 30, -1));

        maxButton.setText("Calculate");
        maxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxButtonActionPerformed(evt);
            }
        });
        jPanel1.add(maxButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        minTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        minTitle.setText("Finds minimum of two numbers");
        jPanel1.add(minTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        minText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minText1ActionPerformed(evt);
            }
        });
        jPanel1.add(minText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 30, -1));

        minButton.setText("Calculate");
        minButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minButtonActionPerformed(evt);
            }
        });
        jPanel1.add(minButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        powTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        powTitle.setText("Finds Power of two numbers");
        jPanel1.add(powTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        powText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powText1ActionPerformed(evt);
            }
        });
        jPanel1.add(powText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 30, -1));

        powText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powText2ActionPerformed(evt);
            }
        });
        jPanel1.add(powText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 30, -1));

        powButton.setText("Calculate");
        powButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButtonActionPerformed(evt);
            }
        });
        jPanel1.add(powButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        hypoTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        hypoTitle.setText("Finds Hypotenuse of two sIDE LENGTHS");
        jPanel1.add(hypoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        hypoText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypoText1ActionPerformed(evt);
            }
        });
        jPanel1.add(hypoText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 30, -1));

        hypoButton.setText("Calculate");
        hypoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(hypoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        floorTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        floorTitle.setText("rOUNDS DOWN DECIMAL NUMBER TO NEAREST WHOLE");
        jPanel1.add(floorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        floorText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorText1ActionPerformed(evt);
            }
        });
        jPanel1.add(floorText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 30, -1));

        floorButton.setText("Calculate");
        floorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(floorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        cielTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        cielTitle.setText("rOUNDS UP DECIMAL NUMBER TO NEAREST WHOLE");
        jPanel1.add(cielTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        cielText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cielText1ActionPerformed(evt);
            }
        });
        jPanel1.add(cielText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 30, -1));

        cielButton.setText("Calculate");
        cielButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cielButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cielButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        sqrtTitle.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        sqrtTitle.setText("fINDS SQUARE ROOT OF A NUMBER");
        jPanel1.add(sqrtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        sqrtText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtText1ActionPerformed(evt);
            }
        });
        jPanel1.add(sqrtText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 30, -1));

        toRadText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRadText1ActionPerformed(evt);
            }
        });
        jPanel1.add(toRadText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 30, -1));

        sqrtButton.setText("Calculate");
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sqrtButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        answer.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        answer.setText("...");
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, 20));

        calculationLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 12)); // NOI18N
        calculationLabel.setText("Calculation:");
        jPanel1.add(calculationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maxText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxText2ActionPerformed

    private void minText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minText2ActionPerformed

    private void toRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRadButtonActionPerformed
        //Variables
        double toRadA;
        //convert string to integer
        toRadA = Double.parseDouble(toRadText1.getText());
        //Output answer
        answer.setText(String.valueOf(Math.toRadians(toRadA)));
    }//GEN-LAST:event_toRadButtonActionPerformed

    private void maxText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxText1ActionPerformed

    private void hypoText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypoText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypoText2ActionPerformed

    private void maxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxButtonActionPerformed
        //Variables
        double max1;
        double max2;
        //Convert string to integer
        max1 = Double.parseDouble(maxText1.getText());
        max2 = Double.parseDouble(maxText2.getText());
        //Output answer
        answer.setText(String.valueOf(Math.max(max1,max2)));
    }//GEN-LAST:event_maxButtonActionPerformed

    private void minText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minText1ActionPerformed

    private void minButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minButtonActionPerformed
        //Variables
        double min1;
        double min2;
        //Convert string to integer
        min1 = Double.parseDouble(minText1.getText());
        min2 = Double.parseDouble(minText2.getText());
        //Output answer
        answer.setText(String.valueOf(Math.min(min1,min2)));
    }//GEN-LAST:event_minButtonActionPerformed

    private void powText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powText1ActionPerformed

    private void powText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powText2ActionPerformed

    private void powButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButtonActionPerformed
        //Variables
        double pow1;
        double pow2;
        //Convert String to Integer
        pow1 = Double.parseDouble(powText1.getText());
        pow2 = Double.parseDouble(powText2.getText());
        //Ouput answer
        answer.setText(String.valueOf(Math.pow(pow1,pow2)));
    }//GEN-LAST:event_powButtonActionPerformed

    private void hypoText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypoText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypoText1ActionPerformed

    private void hypoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypoButtonActionPerformed
        //Variables
        double sideA;
        double sideB;
        //Conevert string to integer
        sideA = Double.parseDouble(hypoText1.getText());
        sideB = Double.parseDouble(hypoText2.getText());
        //Output Answer
        answer.setText(String.valueOf(Math.hypot(sideA, sideB)));
    }//GEN-LAST:event_hypoButtonActionPerformed

    private void floorText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorText1ActionPerformed

    private void floorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorButtonActionPerformed
        //Variables
        double floorA;
        //Conver string to integer
        floorA =Double.parseDouble(floorText1.getText());
        //Output answer
        answer.setText(String.valueOf(Math.floor(floorA)));
    }//GEN-LAST:event_floorButtonActionPerformed

    private void cielText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cielText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cielText1ActionPerformed

    private void cielButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cielButtonActionPerformed
        //Variables
        double cielA;
        //Converts string to integer
        cielA = Double.parseDouble(cielText1.getText());
        //Output answer
        answer.setText(String.valueOf(Math.ceil(cielA)));
    }//GEN-LAST:event_cielButtonActionPerformed

    private void sqrtText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrtText1ActionPerformed

    private void toRadText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRadText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toRadText1ActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        //Variables
        double sqrtA;
        //convert string to integer
        sqrtA = Double.parseDouble(sqrtText1.getText());
        //Output answer
        answer.setText(String.valueOf(Math.sqrt(sqrtA)));
    }//GEN-LAST:event_sqrtButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(methods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(methods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(methods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(methods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new methods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer;
    private javax.swing.JLabel calculationLabel;
    private javax.swing.JButton cielButton;
    private javax.swing.JTextField cielText1;
    private javax.swing.JLabel cielTitle;
    private javax.swing.JButton floorButton;
    private javax.swing.JTextField floorText1;
    private javax.swing.JLabel floorTitle;
    private javax.swing.JButton hypoButton;
    private javax.swing.JTextField hypoText1;
    private javax.swing.JTextField hypoText2;
    private javax.swing.JLabel hypoTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maxButton;
    private javax.swing.JTextField maxText1;
    private javax.swing.JTextField maxText2;
    private javax.swing.JLabel maxTitle;
    private javax.swing.JButton minButton;
    private javax.swing.JTextField minText1;
    private javax.swing.JTextField minText2;
    private javax.swing.JLabel minTitle;
    private javax.swing.JButton powButton;
    private javax.swing.JTextField powText1;
    private javax.swing.JTextField powText2;
    private javax.swing.JLabel powTitle;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JTextField sqrtText1;
    private javax.swing.JLabel sqrtTitle;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toRadButton;
    private javax.swing.JTextField toRadText1;
    private javax.swing.JLabel toRadTitle;
    // End of variables declaration//GEN-END:variables
}
